FROM python:3.7-alpine

RUN mkdir -p /app
WORKDIR /app

# The following two lines would be removed once statefun would be published to PyPI
COPY statefun-1.1.0-py3-none-any.whl /app
RUN pip install statefun-1.1.0-py3-none-any.whl

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY main.py /app

EXPOSE 8000

CMD ["gunicorn", "-w 4", "main:app"]

